version: "3.4"
services:
  rtorrent:
    container_name: rtorrent
    image: romancin/rutorrent-flood:0.9.8
    tty: true
    restart: unless-stopped
    network_mode: host 
    environment:
      - PUID=0 # default user id, defined in .env
      - PGID=0 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - CREATE_SUBDIR_BY_TRACKERS=NO
      - SSL_ENABLED=NO
      - RT_TOKEN=
      - RT_MASTERS=
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/rtorrent:/config # config files
      - rtorrent_sock:/data
    ports:
      - 8853:80
      - 32316:52316
      - 3333:3000
      - 51415:51415

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - 6767:6767
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=22
    volumes:
      - ${ROOT}/config/lidarr:/config
      - ${ROOT}/complete/music:/music
      - ${ROOT}/downloads:/downloads
    ports:
      - 8686:8686
  overseerr:
    container_name: overseerr
    image: sctx/overseerr
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    ports:
      - 5055:5055
    volumes:
      - ${ROOT}/config/overseerr:/app/config
  emby:
    image: linuxserver/emby:4.5.4.0-ls78
    container_name: emby
    restart: unless-stopped
    environment:
      - UMASK_SET # umask setting of Emby, default if left unset is 022.
      - TZ=${TZ} # Specify a timezone to use (e.g. Europe/London)
      - PUID=${PUID} # ID of user
      - PGID=${PGID} # ID of the group to assign to managed files
    volumes:
      - ${ROOT}/transcode:/transcode # Path for transcoding folder, optional.
      - ${ROOT}/complete:/data/content # Media goes here
      - ${ROOT}/config/emby:/config # Emby data storage location. This can grow very large, 50gb+ is likely for a large collection.
    ports:
      - 8920:8920/tcp # Application HTTPS port (optional)
      - 8096:8096/tcp # Application HTTP port

volumes:
  rtorrent_sock:
